variable "project_name" {}
variable instance_types {}
variable enable_irsa {}
variable cluster_version {}
variable ng_min_size {}
variable ng_max_size {}
variable ng_desired_size {}
variable "tags" {}
variable "vpc_id" {}
variable "private_subnets" {}
variable "eks_sg_id" {}